openapi: 3.0.0
info:
  version: 1.0.0
  title: Simple API
  description: A simple API example
paths:
  /:
    get:
      summary: Example GET
      responses:
        '200':
          description: Success
    post:
      summary: Example POST
      responses:
        '200':
          description: Success
